version: "3.9"

services:
  mongodb:
    image: mongo:7
    container_name: mongodb
    restart: unless-stopped

    ports:
      - "${MONGO_PORT:-27017}:27017"

    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER:-dremin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD:-2235}
      MONGO_INITDB_DATABASE: ${MONGO_DB:-auction}

    volumes:
      - mongo_data:/data/db

    command: >
      bash -c "
        mongod --replSet rs0 --bind_ip_all --oplogSize 128 &
        pid=$$!;
        until mongosh --quiet --eval 'db.runCommand({ ping: 1 })' >/dev/null 2>&1; do
          sleep 1;
        done;
        mongosh --quiet --eval '
          try {
            rs.status()
          } catch (e) {
            rs.initiate({
              _id: \"rs0\",
              members: [{ _id: 0, host: \"localhost:27017\" }]
            })
          }
        ';
        wait $$pid
      "

    healthcheck:
      test: >
        mongosh --quiet --eval "rs.status().ok" || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: auction_backend
    restart: unless-stopped
    depends_on:
      mongodb:
        condition: service_healthy
    ports:
      - "${HTTP_SERVER_PORT:-5000}:5000"
    environment:
      DATABASE_URL: mongodb://${MONGO_USER:-dremin}:${MONGO_PASSWORD:-2235}@mongodb:27017/${MONGO_DB:-auction}?authSource=admin
      HTTP_SERVER_HOST: ${HTTP_SERVER_HOST:-0.0.0.0}
      HTTP_SERVER_PORT: ${HTTP_SERVER_PORT:-5000}
      ENV: ${ENV:-production}
    volumes:
      - ./migrations:/app/migrations
      - ./prisma:/app/prisma
    command: >
      sh -c "
        echo 'Waiting for MongoDB to be ready...' &&
        sleep 5 &&
        echo 'Applying migrate-mongo migrations...' &&
        bunx migrate-mongo up &&
        echo 'Starting application...' &&
        bun run index.ts
      "

volumes:
  mongo_data:
